spring.application.name=device-management
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/netpulse_db
spring.data.mongodb.database=netpulse_db

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=30s

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Jackson
spring.jackson.default-property-inclusion=non_null

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
